# Generated by Django 5.0.3 on 2024-11-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("middle_earth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verse",
            name="book",
            field=models.CharField(
                choices=[
                    ("SI", "The Silmarillion"),
                    ("HO", "The Hobbit"),
                    ("FR", "The Fellowship of the Ring"),
                    ("TT", "The Two Towers"),
                    ("RK", "The Return of the King"),
                    ("UT", "Unfinished Tales"),
                    ("CH", "The Children of Hurin"),
                    ("BL", "Beren and Luthien"),
                    ("FG", "The Fall of Gondolin"),
                    ("FN", "The Fall of Numenor"),
                ],
                max_length=100,
            ),
        ),
    ]
